package com.orthoflow.voice.infrastructure.summary;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;

/**
 * The end-of-consultation narrative summary.
 *
 * <p>Distinct from {@code GET /voice/sessions/{id}/summary}, which reads the
 * clinical tables back and is not generated by anything. This is the prose a
 * doctor reads at review — "Examen du 7 septembre : carie récurrente sur 16…"
 * — and it is generated, which is why it is off by default and why nothing it
 * produces is ever written to a clinical record without the doctor editing and
 * saving it themselves.
 *
 * <p>Any OpenAI-compatible chat endpoint works. The default targets Groq,
 * which is where the deployment already holds a key, and the default model is
 * a large one on purpose: a summary runs once per consultation, so latency is
 * irrelevant and the smaller models' French degrades noticeably on medical
 * vocabulary.
 *
 * <p>{@code openai/gpt-oss-120b} rather than {@code llama-3.3-70b-versatile}:
 * the Llama model is gated behind Groq's enterprise tier and a standard key
 * gets a 404 from it, which would make the default configuration fail for most
 * deployments. {@code qwen/qwen3.8-27b} is the other reasonable choice and in
 * testing produced slightly better French clinical terminology, but the larger
 * model follows the "report only what is here, invent nothing" instruction
 * more reliably — and for a document a dentist signs, faithfulness beats idiom.
 */
@Component
@ConfigurationProperties(prefix = "orthoflow.voice.summary")
@Getter
@Setter
public class VoiceSummaryProperties {

    /**
     * When false, no model is called: {@code POST /voice/sessions/{id}/summarize}
     * answers with the records rendered deterministically instead, which
     * sends nothing to a third party and is always exact.
     */
    private boolean enabled = false;

    /** The primary route's vendor: {@code groq} or {@code deepseek}. */
    private String provider = "groq";

    /**
     * Tried in order, as {@code vendor:model}, when the primary fails or
     * produces a summary that does not match the records. Each vendor needs
     * its key under {@code orthoflow.voice.providers}.
     */
    private List<String> fallbacks = new ArrayList<>(List.of("groq:qwen/qwen3.8-27b", "deepseek:deepseek-flash"));

    private String apiKey = "";

    private String model = "openai/gpt-oss-120b";

    /**
     * OpenAI-compatible chat root for the primary vendor, no trailing slash.
     * Blank uses that vendor's endpoint from {@code orthoflow.voice.providers}.
     */
    private String baseUrl = "";

    /**
     * Consultations are short and a summary is not a reasoning task, but a
     * long examination produces a lot of audit rows, so this is more generous
     * than the NLU's equivalent.
     */
    private int timeoutMs = 30000;

    private int maxOutputTokens = 1200;

    /**
     * The output language, as a full language name the model will recognise.
     * French because that is what the clinicians using this speak; an English
     * or Arabic deployment sets it here rather than editing the prompt.
     */
    private String language = "French";

    /**
     * Ceiling on how many audited commands are fed to the model. A session
     * past this is truncated to the most recent, with the prompt saying so —
     * a summary of most of a consultation beats a timeout.
     */
    private int maxCommands = 200;
}
